QUESTIONS = {
    "Python Developer": [
        {"id": 1, "category": "Easy", "question": "Explain list vs tuple.", "ideal_answer": "Lists are mutable, tuples are immutable.", "keywords": ["mutable", "immutable", "brackets"]},
        {"id": 2, "category": "Easy", "question": "What is a dictionary?", "ideal_answer": "A mutable, unordered collection of key-value pairs.", "keywords": ["key", "value", "hashable"]},
        {"id": 3, "category": "Easy", "question": "Explain def vs lambda.", "ideal_answer": "Def defines standard functions, lambda defines anonymous single-expression functions.", "keywords": ["anonymous", "single-expression", "function"]},
        {"id": 4, "category": "Easy", "question": "What is PEP 8?", "ideal_answer": "The official style guide for Python code.", "keywords": ["style guide", "readability", "formatting"]},
        {"id": 5, "category": "Easy", "question": "How do you import modules?", "ideal_answer": "Using the import keyword.", "keywords": ["import", "from", "as"]},
        {"id": 6, "category": "Medium", "question": "Explain decorators.", "ideal_answer": "Functions that modify the behavior of another function.", "keywords": ["wrapper", "modify", "higher-order"]},
        {"id": 7, "category": "Medium", "question": "What are generators?", "ideal_answer": "Functions that yield values one at a time using yield.", "keywords": ["yield", "iterator", "memory"]},
        {"id": 8, "category": "Medium", "question": "Threading vs Multiprocessing?", "ideal_answer": "Threading shares memory, multiprocessing uses separate memory spaces.", "keywords": ["threads", "processes", "gil", "memory"]},
        {"id": 9, "category": "Medium", "question": "What is the GIL?", "ideal_answer": "Global Interpreter Lock prevents multiple native threads from executing Python bytecodes at once.", "keywords": ["lock", "interpreter", "concurrency"]},
        {"id": 10, "category": "Medium", "question": "Explain context managers.", "ideal_answer": "Used for resource management, usually with the 'with' statement.", "keywords": ["with", "__enter__", "__exit__", "resources"]},
        {"id": 11, "category": "Hard", "question": "What are metaclasses?", "ideal_answer": "Classes of classes that define how a class behaves.", "keywords": ["type", "instantiation", "class creation"]},
        {"id": 12, "category": "Hard", "question": "Explain asyncio in Python.", "ideal_answer": "A library to write concurrent code using the async/await syntax.", "keywords": ["event loop", "async", "await", "coroutine"]},
        {"id": 13, "category": "Hard", "question": "How does Python handle memory management?", "ideal_answer": "Using a private heap space and a garbage collector.", "keywords": ["reference counting", "garbage collection", "heap"]},
        {"id": 14, "category": "Hard", "question": "Deep vs shallow copy?", "ideal_answer": "Shallow copies references, deep recursively copies objects.", "keywords": ["reference", "recursion", "copy module"]},
        {"id": 15, "category": "Hard", "question": "What are descriptors?", "ideal_answer": "Object attributes with binding behavior defined by __get__, __set__, or __delete__.", "keywords": ["__get__", "__set__", "binding", "property"]}
    ],
    "Java Developer": [
        {"id": 1, "category": "Easy", "question": "What is OOP?", "ideal_answer": "Object-Oriented Programming based on objects.", "keywords": ["encapsulation", "inheritance", "polymorphism"]},
        {"id": 2, "category": "Easy", "question": "String vs StringBuilder?", "ideal_answer": "String is immutable, StringBuilder is mutable.", "keywords": ["immutable", "mutable", "thread-safe"]},
        {"id": 3, "category": "Easy", "question": "Array vs ArrayList?", "ideal_answer": "Array is fixed size, ArrayList is dynamic.", "keywords": ["fixed", "dynamic", "collections"]},
        {"id": 4, "category": "Easy", "question": "What does static mean?", "ideal_answer": "Belongs to the class, not an instance.", "keywords": ["class-level", "memory", "instance"]},
        {"id": 5, "category": "Easy", "question": "Checked vs unchecked exceptions?", "ideal_answer": "Checked are checked at compile-time, unchecked at runtime.", "keywords": ["compile-time", "runtime", "RuntimeException"]},
        {"id": 6, "category": "Medium", "question": "How does HashMap work?", "ideal_answer": "Stores key-value pairs using a hash table.", "keywords": ["hashcode", "equals", "buckets", "collisions"]},
        {"id": 7, "category": "Medium", "question": "Explain multithreading.", "ideal_answer": "Executing multiple threads simultaneously.", "keywords": ["Runnable", "Thread class", "concurrency"]},
        {"id": 8, "category": "Medium", "question": "What is Garbage Collection?", "ideal_answer": "Automatic memory management freeing unreferenced objects.", "keywords": ["memory", "finalize", "JVM"]},
        {"id": 9, "category": "Medium", "question": "Interface vs Abstract Class?", "ideal_answer": "Interfaces have no state, abstract classes can.", "keywords": ["multiple inheritance", "implements", "extends"]},
        {"id": 10, "category": "Medium", "question": "Explain the Collections framework.", "ideal_answer": "A unified architecture for representing and manipulating collections.", "keywords": ["Set", "List", "Queue", "Map"]},
        {"id": 11, "category": "Hard", "question": "Explain JVM architecture.", "ideal_answer": "ClassLoader, Memory Area, Execution Engine.", "keywords": ["classloader", "heap", "stack", "JIT"]},
        {"id": 12, "category": "Hard", "question": "What are ClassLoaders?", "ideal_answer": "Subsystems of JVM used to load class files.", "keywords": ["Bootstrap", "Extension", "Application"]},
        {"id": 13, "category": "Hard", "question": "Explain the Streams API.", "ideal_answer": "Functional-style operations on streams of elements.", "keywords": ["filter", "map", "reduce", "lambda"]},
        {"id": 14, "category": "Hard", "question": "Explain Concurrency utilities.", "ideal_answer": "Classes like ExecutorService and CountDownLatch.", "keywords": ["Executor", "Locks", "Callable", "Future"]},
        {"id": 15, "category": "Hard", "question": "How to fix memory leaks in Java?", "ideal_answer": "Remove unused references, close resources.", "keywords": ["profiler", "references", "VisualVM", "close()"]}
    ],
    "AI ML Engineer": [
        {"id": 1, "category": "Easy", "question": "Supervised vs Unsupervised learning?", "ideal_answer": "Supervised uses labeled data, unsupervised uses unlabeled.", "keywords": ["labeled", "unlabeled", "target"]},
        {"id": 2, "category": "Easy", "question": "What is overfitting?", "ideal_answer": "Model learns noise instead of signal.", "keywords": ["training data", "generalization", "variance"]},
        {"id": 3, "category": "Easy", "question": "Name evaluation metrics.", "ideal_answer": "Accuracy, precision, recall, F1-score.", "keywords": ["accuracy", "precision", "recall", "F1"]},
        {"id": 4, "category": "Easy", "question": "Train vs Test split?", "ideal_answer": "Splitting data to evaluate model generalization.", "keywords": ["evaluation", "split", "generalization"]},
        {"id": 5, "category": "Easy", "question": "Explain linear regression.", "ideal_answer": "Predicting a continuous target using a linear equation.", "keywords": ["continuous", "line of best fit", "slope"]},
        {"id": 6, "category": "Medium", "question": "What is a CNN?", "ideal_answer": "Neural network with convolutional layers, good for images.", "keywords": ["convolution", "pooling", "spatial", "images"]},
        {"id": 7, "category": "Medium", "question": "What is an RNN?", "ideal_answer": "Network with loops, good for sequential data.", "keywords": ["sequence", "time-series", "hidden state"]},
        {"id": 8, "category": "Medium", "question": "Explain Gradient Descent.", "ideal_answer": "Optimization algorithm to minimize loss.", "keywords": ["learning rate", "loss function", "weights", "minimize"]},
        {"id": 9, "category": "Medium", "question": "Bias vs Variance tradeoff?", "ideal_answer": "Balancing underfitting (high bias) and overfitting (high variance).", "keywords": ["underfitting", "overfitting", "error"]},
        {"id": 10, "category": "Medium", "question": "What is regularization?", "ideal_answer": "Adding a penalty to the loss to prevent overfitting.", "keywords": ["L1", "L2", "penalty", "overfitting"]},
        {"id": 11, "category": "Hard", "question": "Explain Transformers.", "ideal_answer": "Architecture relying entirely on attention mechanisms.", "keywords": ["self-attention", "encoder", "decoder"]},
        {"id": 12, "category": "Hard", "question": "Math behind backpropagation?", "ideal_answer": "Using the chain rule to compute gradients.", "keywords": ["chain rule", "gradients", "derivatives"]},
        {"id": 13, "category": "Hard", "question": "Vanishing gradient problem?", "ideal_answer": "Gradients become too small to update early layers.", "keywords": ["activation function", "deep networks", "sigmoid"]},
        {"id": 14, "category": "Hard", "question": "How does attention work?", "ideal_answer": "Weighing the importance of different input parts.", "keywords": ["queries", "keys", "values", "weights"]},
        {"id": 15, "category": "Hard", "question": "Explain ensemble methods.", "ideal_answer": "Combining multiple models to improve performance.", "keywords": ["bagging", "boosting", "random forest"]}
    ],
    "Data Analyst": [
        {"id": 1, "category": "Easy", "question": "What is normalization?", "ideal_answer": "Organizing data to reduce redundancy.", "keywords": ["redundancy", "tables", "normal forms"]},
        {"id": 2, "category": "Easy", "question": "Explain SQL JOINs.", "ideal_answer": "Combining rows from two or more tables.", "keywords": ["inner", "left", "right", "outer"]},
        {"id": 3, "category": "Easy", "question": "What is GROUP BY?", "ideal_answer": "Grouping rows sharing a property to apply aggregates.", "keywords": ["aggregate", "sum", "count"]},
        {"id": 4, "category": "Easy", "question": "Handling missing values?", "ideal_answer": "Imputation, deletion, or keeping them.", "keywords": ["impute", "drop", "mean", "null"]},
        {"id": 5, "category": "Easy", "question": "Mean vs Median?", "ideal_answer": "Average vs middle value of a sorted dataset.", "keywords": ["average", "middle", "outliers"]},
        {"id": 6, "category": "Medium", "question": "What are window functions?", "ideal_answer": "Functions operating on a set of rows related to the current row.", "keywords": ["OVER", "PARTITION BY", "rank"]},
        {"id": 7, "category": "Medium", "question": "Explain A/B testing.", "ideal_answer": "Comparing two versions to see which performs better.", "keywords": ["control", "variant", "conversion"]},
        {"id": 8, "category": "Medium", "question": "What is a p-value?", "ideal_answer": "Probability of observing results assuming null hypothesis is true.", "keywords": ["significance", "null hypothesis", "probability"]},
        {"id": 9, "category": "Medium", "question": "Explain ETL.", "ideal_answer": "Extract, Transform, Load data pipeline process.", "keywords": ["extract", "transform", "load", "warehouse"]},
        {"id": 10, "category": "Medium", "question": "Best practices for data visualization?", "ideal_answer": "Keep it simple, label axes, choose right chart type.", "keywords": ["clarity", "audience", "labels"]},
        {"id": 11, "category": "Hard", "question": "How do you optimize a slow query?", "ideal_answer": "Use indexes, avoid SELECT *, optimize joins.", "keywords": ["execution plan", "index", "EXPLAIN"]},
        {"id": 12, "category": "Hard", "question": "Predictive vs Prescriptive modeling?", "ideal_answer": "Predicting what happens vs recommending actions.", "keywords": ["forecast", "recommendation", "outcomes"]},
        {"id": 13, "category": "Hard", "question": "Explain K-Means clustering.", "ideal_answer": "Partitioning data into K distinct clusters based on distance.", "keywords": ["centroids", "distance", "unsupervised"]},
        {"id": 14, "category": "Hard", "question": "What is time series analysis?", "ideal_answer": "Analyzing data points collected over time intervals.", "keywords": ["seasonality", "trend", "stationarity"]},
        {"id": 15, "category": "Hard", "question": "Define statistical power.", "ideal_answer": "Probability of correctly rejecting a false null hypothesis.", "keywords": ["Type II error", "sample size", "effect size"]}
    ],
    "Web Developer": [
        {"id": 1, "category": "Easy", "question": "HTML semantics?", "ideal_answer": "Using tags that convey meaning like <article> or <nav>.", "keywords": ["meaning", "accessibility", "SEO"]},
        {"id": 2, "category": "Easy", "question": "CSS Box Model?", "ideal_answer": "Content, padding, border, and margin.", "keywords": ["padding", "margin", "border", "content"]},
        {"id": 3, "category": "Easy", "question": "let vs var vs const?", "ideal_answer": "Block scope for let/const, function scope for var.", "keywords": ["scope", "block", "hoisting", "reassignment"]},
        {"id": 4, "category": "Easy", "question": "GET vs POST?", "ideal_answer": "GET retrieves data, POST submits data.", "keywords": ["retrieve", "submit", "body", "url"]},
        {"id": 5, "category": "Easy", "question": "What is the DOM?", "ideal_answer": "Document Object Model, a tree representation of the page.", "keywords": ["tree", "nodes", "javascript", "document"]},
        {"id": 6, "category": "Medium", "question": "Explain REST APIs.", "ideal_answer": "Stateless architectural style using HTTP methods.", "keywords": ["stateless", "endpoints", "JSON", "HTTP"]},
        {"id": 7, "category": "Medium", "question": "What is CORS?", "ideal_answer": "Cross-Origin Resource Sharing security feature.", "keywords": ["headers", "origin", "security", "browser"]},
        {"id": 8, "category": "Medium", "question": "Event delegation?", "ideal_answer": "Attaching a single listener to a parent element.", "keywords": ["bubbling", "parent", "target", "memory"]},
        {"id": 9, "category": "Medium", "question": "LocalStorage vs SessionStorage?", "ideal_answer": "Local persists after close, session clears on close.", "keywords": ["persistence", "browser close", "storage API"]},
        {"id": 10, "category": "Medium", "question": "Explain Promises.", "ideal_answer": "Object representing eventual completion of async operation.", "keywords": ["resolve", "reject", "then", "async"]},
        {"id": 11, "category": "Hard", "question": "What are JWTs?", "ideal_answer": "JSON Web Tokens used for stateless authentication.", "keywords": ["payload", "signature", "authentication", "stateless"]},
        {"id": 12, "category": "Hard", "question": "Explain WebSockets.", "ideal_answer": "Protocol for persistent bi-directional communication.", "keywords": ["real-time", "persistent", "bidirectional", "TCP"]},
        {"id": 13, "category": "Hard", "question": "XSS vs CSRF?", "ideal_answer": "XSS injects scripts, CSRF forces unauthorized actions.", "keywords": ["cross-site scripting", "forgery", "injection", "tokens"]},
        {"id": 14, "category": "Hard", "question": "Web performance optimization?", "ideal_answer": "Minification, lazy loading, caching, CDN.", "keywords": ["minification", "lazy load", "CDN", "cache"]},
        {"id": 15, "category": "Hard", "question": "What are Microservices?", "ideal_answer": "Architectural style structuring an app as a collection of services.", "keywords": ["decoupled", "independent", "services", "scaling"]}
    ]
}

def get_role_questions(role):
    return QUESTIONS.get(role, [])